apiVersion: apps/v1
kind: Deployment
metadata:
  name: security
spec:
  selector:
    matchLabels:
      app: security
  template:
    metadata:
      labels:
        app: security
    spec:
      containers:
      - name: security
        image: okosodovictor/security
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
