apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: payment-gateway

resources:
  - security/deployment.yaml
  - security/service.yaml
  - payment/deployment.yaml
  - payment/service.yaml
  - ingress.yaml